---
title: "Final Analysis"
author: "J.E. Hug"
date: "5/11/2021"
output: html_document
---


This can be entirely run making sure the 3 csv's are in a folder called "data" within the current working directory of this Rmd file.

```{r setup, include=TRUE}
library(tidyverse) # data manipulation and plotting
library(magrittr) # extra pipes
library(geepack) # GEE 
library(lme4) # mixed model
library(glmnet) # Lasso
library(lindia) # regression diagnostic plots
library(car) #heteroskedastic SE
library(gridExtra) # plotting
library(selectiveInference) # LASSO selective inference
options(scipen=10)
```


# The Cleaning of the initial data

```{r prison data}
# read in prison data
prison <- read.csv(file = 
                     "./data/california_jail_county_monthly_1995_2020.csv")

# San Francisco county has no revenue
prison %<>% filter(census_county_name !=  "San Francisco County") %>% 
  filter(year <= 2019 & year >=2005)

# group by county and aggregate into yearly data

prisonByCounty <- prison %>% 
  filter(year <= 2019 & year >=2005)

# now can aggregate by variable into yearly data


prisonclean <- prisonByCounty %>% group_by(fips_county_code,year) %>%
  dplyr::select(-c(jurisdiction,month,date,census_county_name,fips_state_code,fips_state_county_code)) %>% 
  summarise_all(.funs = mean)



```


```{r revenue data}
# make a county FIPS column that we can join on
countiesrevenues <-
  c("Alameda",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc" ,
    "Mono"   ,
    "Monterey"     ,
    "Napa" ,
    "Nevada" ,
    "Orange"      ,
    "Placer"    ,
    "Plumas"    ,
    "Riverside" ,
    "Sacramento"     ,
    "San Benito",
    "San Bernardino" ,
    "San Diego"  ,
    "San Joaquin",
    "San Luis Obispo" ,
    "San Mateo"  ,
    "Santa Barbara",
    "Santa Clara" ,
    "Santa Cruz",
    "Shasta"    ,
    "Sierra"  ,
    "Siskiyou"  ,
    "Solano"     ,
    "Sonoma",
    "Stanislaus"     ,
    "Sutter"  ,
    "Tehama"     ,
    "Trinity"      ,
    "Tulare"     ,
    "Tuolumne" ,
    "Ventura",
    "Yolo",
    "Yuba"
  )

countyFIPS <- sort(unique(prison$fips_county_code))

countyFIPStable <- data.frame(Entity.Name = countiesrevenues,fips_county_code = countyFIPS)

revenue <- read.csv(file = "./data/County_Revenues_Per_Capita.csv")

revenue %<>% filter(Entity.Name!=  "Alpine") %>% 
  filter(Fiscal.Year <= 2019 & Fiscal.Year >=2005) %>% 
  mutate(year = Fiscal.Year) %>% dplyr::select(-Fiscal.Year)

revenueclean <- inner_join(revenue,countyFIPStable, by = c("Entity.Name"))

```



```{r gdp data}
gdpcalif <- read.csv("./data/gdpcalif.csv")

gdpcalifclean <- gdpcalif %>% filter(Description == "All industry total") %>% 
  mutate(fips_county_code=as.numeric(GeoFIPS)-6000) %>% 
  filter(fips_county_code != 0) %>% 
  dplyr::select(-c(Description,Unit,Region,TableName,GeoFIPS,GeoName,
            IndustryClassification, LineCode)) %>% 
  pivot_longer(cols=-c(fips_county_code)) %>% rename(GDP = value) %>% 
  mutate(year =as.numeric(str_split(name,"X",simplify = TRUE)[str_split(name,"X",simplify = TRUE)!= ""])) %>% 
  filter(year <= 2019 & year >=2005) %>% mutate(GDP = as.numeric(GDP)) %>% 
  dplyr::select(-name)

```






```{r combine all 3 datasets}
# Put all 3 datasets together

revAndGDP <- inner_join(gdpcalifclean,revenueclean,by = c("fips_county_code","year"))

combinedData <- inner_join(revAndGDP,prisonclean,by = c("fips_county_code","year"))

# cut variables with all NA
combinedData %<>%  mutate(GDP.Per.Capita = GDP/Estimated.Population) %>%
  dplyr::select(-c(avg_inmate_need_reg_med_attent,adp_of_maximum_security_inmates,
            adp_of_medium_security_inmates,avg_inmates_get_mental_heath_bed,
            total_juv_in_custody,avg_own_inmate_housed_elsewhere,
            avg_fed_inmate_housed_contract,avg_state_inmate_housed_contract,
            avg_local_inmate_housed_contract, avg_inmate_wait_transport_prison,
            adp_of_minimum_security_inmates, avg_inmates_get_medical_bed,
            avg_inmates_need_reg_ment_health,day_of_highest_count))

# standardized
combinedDataal <- combinedData %>% dplyr::select(-
    c(fips_county_code,
    GDP,
    year,
    Entity.Name,
    Total.Revenues,
    Estimated.Population,
    Revenues.Per.Capita,
    GDP.Per.Capita,
    highest_inmate_count)) %>% 
  mutate_all(function(x) x/combinedData$total_num_persons_booked) %>% 
  mutate(fips_county_code = combinedData$fips_county_code,year = combinedData$year)

# scale the covariates

combinedDataal %<>% mutate_at(vars(-fips_county_code,-year,-total_num_persons_booked),.funs = scale) 


combinedStandard <- inner_join(revAndGDP,combinedDataal, by = c("fips_county_code","year")) %>% 
  mutate(GDP.Per.Capita = GDP/Estimated.Population)




combinedStandard %<>% dplyr::select(
  avg_daily_pop_unsentenced_male ,
  avg_daily_pop_unsentenced_female,
  avg_daily_pop_sentenced_male,
  avg_daily_pop_sentenced_male,
  avg_daily_pop_sentenced_female ,
  avg_felony_inmate_unsentenced  ,
  avg_felony_inmate_sentenced , GDP.Per.Capita ,
  Revenues.Per.Capita,fips_county_code
) %>% na.omit()

length(unique(combinedStandard$fips_county_code))

```


```{r OLS}

formula1 <- log(GDP.Per.Capita) ~ avg_daily_pop_unsentenced_male + avg_daily_pop_unsentenced_female+avg_daily_pop_sentenced_male+
  avg_daily_pop_sentenced_male+ avg_daily_pop_sentenced_female +
  avg_felony_inmate_unsentenced  +  avg_felony_inmate_sentenced


formula2 <- log(Revenues.Per.Capita) ~ avg_daily_pop_unsentenced_male + avg_daily_pop_unsentenced_female+avg_daily_pop_sentenced_male+
  avg_daily_pop_sentenced_male+ avg_daily_pop_sentenced_female +
  avg_felony_inmate_unsentenced  +  avg_felony_inmate_sentenced  


lm1 <- lm(formula1, data = combinedStandard)
summary(lm1)
hc3lm1 <- sqrt(diag(hccm(lm1, type = "hc3")))
plot(lm1)

lm2 <- lm(formula2, data = combinedStandard)
summary(lm2)
hc3lm2 <- sqrt(diag(hccm(lm2, type = "hc3")))
plot(lm2)


lm1p1 <- lindia::gg_diagnose(lm1, plot.all = F)$resleverage
lm1p2 <- lindia::gg_diagnose(lm1, plot.all = F)$res_fitted
lm1p3 <- lindia::gg_diagnose(lm1, plot.all = F)$qqplot
lm1p4 <- lindia::gg_diagnose(lm1, plot.all = F)$cooksd


grid.arrange(lm1p1,lm1p2,lm1p3,lm1p4,ncol =2, nrow =2, top = "log(GDP per capita) response")



lm2p1 <- lindia::gg_diagnose(lm2, plot.all = F)$resleverage
lm2p2 <- lindia::gg_diagnose(lm2, plot.all = F)$res_fitted
lm2p3 <- lindia::gg_diagnose(lm2, plot.all = F)$qqplot
lm2p4 <- lindia::gg_diagnose(lm2, plot.all = F)$cooksd

grid.arrange(lm2p1,lm2p2,lm2p3,lm2p4,ncol =2, nrow =2, top = "log(Revenue per capita) response")

```

```{r LASSO}

# make lasso covariate matrix

lassocov <- combinedStandard %>% 
  dplyr::select(avg_daily_pop_unsentenced_male ,avg_daily_pop_unsentenced_female,avg_daily_pop_sentenced_male,
  avg_daily_pop_sentenced_male, avg_daily_pop_sentenced_female ,
  avg_felony_inmate_unsentenced  ,  avg_felony_inmate_sentenced  )

x <- as.matrix(lassocov)

ygdp <- log(combinedStandard$Revenues.Per.Capita)

yrev <- log(combinedStandard$GDP.Per.Capita)


# GDP model get the lambda

lass1<- cv.glmnet(x=x, y = ygdp)

lambda1 <- lass1$lambda.min

fit1 <- glmnet(x=x,y=ygdp,standardize = FALSE)

coef1 <- coef(fit1, s= lambda1)

coef1


# Revenue model 


lass2 <- cv.glmnet(x=x, y = yrev)

lambda2 <- lass2$lambda.min

fit2 <- glmnet(x=x,y=yrev,standardize = FALSE)

coef2<- coef(fit2, s= lambda2)

coef2


# selective inference standard errors

# these do not seem to give proper results so we do not include, 
# in addition the results given are not very informative

selinf1 <-fixedLassoInf(x= x , y = ygdp,
              beta = coef(fit1, x = x, y = ygdp, s= lambda1/length(ygdp))[-1] ,lambda = lambda1)
selinf1


```




``` {r GEE}



gee1ind <- geepack::geeglm(formula1, data = combinedStandard, id = fips_county_code,corstr = "independence")
summary(gee1ind)

gee2ind <- geepack::geeglm(formula2, data = combinedStandard, id = fips_county_code,corstr = "independence")
summary(gee2ind)


gee1uns <- geepack::geeglm(formula1, data = combinedStandard, id = fips_county_code,corstr = "unstructured")
summary(gee1uns)


gee2uns <- geepack::geeglm(formula2, data = combinedStandard, id = fips_county_code,corstr = "unstructured")
summary(gee2uns)



```




```{r mixed model}

# we define the models with a random slope parameter

mformula1 <- log(GDP.Per.Capita) ~ (1|fips_county_code)+avg_daily_pop_unsentenced_male + avg_daily_pop_unsentenced_female+avg_daily_pop_sentenced_male+
  avg_daily_pop_sentenced_male+ avg_daily_pop_sentenced_female +
  avg_felony_inmate_unsentenced  +  avg_felony_inmate_sentenced  


mformula2 <- log(Revenues.Per.Capita) ~ (1|fips_county_code)+avg_daily_pop_unsentenced_male + avg_daily_pop_unsentenced_female+avg_daily_pop_sentenced_male+
  avg_daily_pop_sentenced_male+ avg_daily_pop_sentenced_female+
  avg_felony_inmate_unsentenced  +  avg_felony_inmate_sentenced  


mlm1 <- lmer(mformula1,data = combinedStandard)
summary(mlm1)

mlm2 <- lmer(mformula2,data = combinedStandard)
summary(mlm2)




# standardize all coefficients with the prison population
```



